import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  platformSidebar: [
    "intro",

    {
      type: "category",
      label: "Getting Started",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "getting-started",
        },
      ],
    },

    {
      type: "category",
      label: "Components",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "components",
        },
      ],
    },

    {
      type: "category",
      label: "Features",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "features",
        },
      ],
    },

    {
      type: "category",
      label: "API",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "api",
        },
      ],
    },

    {
      type: "category",
      label: "Advanced",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "advanced",
        },
      ],
    },

    {
      type: "category",
      label: "Tutorial - Basics",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "tutorial-basics",
        },
      ],
    },

    {
      type: "category",
      label: "Tutorial - Extras",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "tutorial-extras",
        },
      ],
    },
  ],
};

export default sidebars;
