backend:
  name: github
  repo: GowtamPaul5120/GowtamPaul5120.github.io
  branch: development
  base_url: https://platformnx-cms-auth.gowtampaul16.workers.dev
  auth_endpoint: /auth
  squash_merges: true

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: docs
    label: Documentation
    folder: docs
    create: true
    extension: md
    format: frontmatter
    nested:
      depth: 10
      summary: "{{title}}"
    meta:
      path:
        label: "File Path"
        widget: string
        index_file: index
    fields:
      - { label: "Title", name: title, widget: string }
      - {
          label: "Sidebar Position",
          name: sidebar_position,
          widget: number,
          required: false,
        }
      - {
          label: "Description",
          name: description,
          widget: text,
          required: false,
        }
      - { label: "Icon", name: icon, widget: string, required: false }
      - { label: "Body", name: body, widget: markdown }

  - name: blog
    label: Blog
    folder: blog
    create: true
    extension: md
    format: frontmatter
    fields:
      - { label: "Title", name: title, widget: string }
      - { label: "Authors", name: authors, widget: string, required: false }
      - { label: "Tags", name: tags, widget: list, required: false }
      - { label: "Body", name: body, widget: markdown }
